---
title: "Sobre"
author: "Costa, W. G."
date: "`r Sys.Date()`"
site: workflowr::wflow_site
url: https://wevertongomescosta.github.io/Manipulacao-dados-e-Analise-Grafica-R/about.html
output:
  workflowr::wflow_html:
    toc: no
editor_options:
  chunk_output_type: console
---

# Curso: Análise Gráfica no R.

Seja bem-vindo(a)! Neste curso, você aprenderá a manipular bancos de dados e a gerar incríveis gráficos 📊📈 utilizando a linguagem R. Durante o curso, abordaremos as principais técnicas e ferramentas de análise gráfica, incluindo a criação de gráficos de dispersão, boxplot, histogramas, gráficos de barras, entre outros.

Este curso foi desenvolvido pelo [prof. Weverton Costa](https://github.com/wevertongomescosta/) para o curso de Análise Gráfica no R oferecido pela [Conecta GEM](https://www.conectagem.com/). O conteúdo do curso é destinado a estudantes e profissionais que desejam aprender a utilizar a linguagem R para análise de dados e criação de gráficos. Todo o material do curso está disponível de forma gratuita e pode ser acessado no repositório GitHub. Além disso, o curso está licenciado sob a Licença Creative Commons Atribuição 4.0 Internacional, o que significa que você pode compartilhar e adaptar o material, desde que atribua crédito ao autor.

Esperamos que este curso seja útil para você e que contribua para o seu aprimoramento profissional. Bom aprendizado!
